settings:
  title: 'jltml.me status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: lemniscate-icon.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: jltml-me # unique identifier
    name: jltml.me
    description: 'The homepage: https://jltml.me' # default=empty
    url: 'https://jltml.me/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: jltml-blog
    name: jltml.me/blog
    description: 'The page that has my blog on it. Pretty self-explanatory.'
    url: 'https://jltml.me/blog'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: jltml-commento
    name: commento.jltml.me
    description: 'The subdomain that hosts Commento (comments) on Heroku. For some reason, it redirects to https://jltml-commento.herokuapp.com, but it works, so meh. This should show downtime if HTTPS/SSL fails.'
    url: 'https://commento.jltml.me'
    method: GET
    expectStatus: 200
    followRedirect: true
